name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation (light)
        uses: Platane/snk/svg-only@v3
        id: snake-light
        with:
          github_user_name: DiveshChauhan123
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Generate snake animation (dark)
        uses: Platane/snk/svg-only@v3
        id: snake-dark
        with:
          github_user_name: DiveshChauhan123
          color_snake: "#F70000"
          color_dots: "#000000,#24292e,#57606a"
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
